
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    profiles: [ frontend, backend ]
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_HOST=${DB_HOSTNAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  app:
    depends_on:
      mysql:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    profiles: [ frontend ]
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src:/app/src

  test-mysql:
    image: mysql:8.3.0
    restart: no
    profiles: [ test ]
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_HOST=${DB_HOSTNAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}